<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="10788" started-at="2015-04-22T07:23:49Z" finished-at="2015-04-22T07:23:59Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="10788" started-at="2015-04-22T07:23:49Z" finished-at="2015-04-22T07:23:59Z">
      <class name="loginagency.IsLoginAgency">
        <test-method status="PASS" signature="inialize()[pri:0, instance:loginagency.IsLoginAgency@770c2e6b]" name="inialize" is-config="true" duration-ms="6987" started-at="2015-04-22T15:23:49Z" finished-at="2015-04-22T15:23:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inialize -->
        <test-method status="FAIL" signature="chkResetPwd()[pri:0, instance:loginagency.IsLoginAgency@770c2e6b]" name="chkResetPwd" duration-ms="3782" started-at="2015-04-22T15:23:56Z" finished-at="2015-04-22T15:23:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [] but found [用户名不存在！]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [] but found [用户名不存在！]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at loginagency.IsLoginAgency.chkResetPwd(IsLoginAgency.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- chkResetPwd -->
      </class> <!-- loginagency.IsLoginAgency -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
